v/lib/python3.11/site-packages/__pycache__/typing_extensions.cpython-311.pyc usr/lib/python3/dist-packages/__pycache__
v/lib/python3.11/site-packages/typing_extensions-4.12.2.dist-info/INSTALLER usr/lib/python3/dist-packages/typing_extensions-4.12.2.dist-info
v/lib/python3.11/site-packages/typing_extensions-4.12.2.dist-info/LICENSE usr/lib/python3/dist-packages/typing_extensions-4.12.2.dist-info
v/lib/python3.11/site-packages/typing_extensions-4.12.2.dist-info/METADATA usr/lib/python3/dist-packages/typing_extensions-4.12.2.dist-info
v/lib/python3.11/site-packages/typing_extensions-4.12.2.dist-info/RECORD usr/lib/python3/dist-packages/typing_extensions-4.12.2.dist-info
v/lib/python3.11/site-packages/typing_extensions-4.12.2.dist-info/WHEEL usr/lib/python3/dist-packages/typing_extensions-4.12.2.dist-info
v/lib/python3.11/site-packages/typing_extensions.py usr/lib/python3/dist-packages