v/lib/python3.11/site-packages/__pycache__/google_auth_httplib2.cpython-311.pyc usr/lib/python3/dist-packages/__pycache__
v/lib/python3.11/site-packages/google_auth_httplib2-0.1.0.dist-info/INSTALLER usr/lib/python3/dist-packages/google_auth_httplib2-0.1.0.dist-info
v/lib/python3.11/site-packages/google_auth_httplib2-0.1.0.dist-info/LICENSE usr/lib/python3/dist-packages/google_auth_httplib2-0.1.0.dist-info
v/lib/python3.11/site-packages/google_auth_httplib2-0.1.0.dist-info/METADATA usr/lib/python3/dist-packages/google_auth_httplib2-0.1.0.dist-info
v/lib/python3.11/site-packages/google_auth_httplib2-0.1.0.dist-info/RECORD usr/lib/python3/dist-packages/google_auth_httplib2-0.1.0.dist-info
v/lib/python3.11/site-packages/google_auth_httplib2-0.1.0.dist-info/WHEEL usr/lib/python3/dist-packages/google_auth_httplib2-0.1.0.dist-info
v/lib/python3.11/site-packages/google_auth_httplib2-0.1.0.dist-info/top_level.txt usr/lib/python3/dist-packages/google_auth_httplib2-0.1.0.dist-info
v/lib/python3.11/site-packages/google_auth_httplib2.py usr/lib/python3/dist-packages