v/lib/python3.11/site-packages/__pycache__/ipaddr.cpython-311.pyc usr/lib/python3/dist-packages/__pycache__
v/lib/python3.11/site-packages/ipaddr-2.2.0.dist-info/COPYING usr/lib/python3/dist-packages/ipaddr-2.2.0.dist-info
v/lib/python3.11/site-packages/ipaddr-2.2.0.dist-info/INSTALLER usr/lib/python3/dist-packages/ipaddr-2.2.0.dist-info
v/lib/python3.11/site-packages/ipaddr-2.2.0.dist-info/METADATA usr/lib/python3/dist-packages/ipaddr-2.2.0.dist-info
v/lib/python3.11/site-packages/ipaddr-2.2.0.dist-info/RECORD usr/lib/python3/dist-packages/ipaddr-2.2.0.dist-info
v/lib/python3.11/site-packages/ipaddr-2.2.0.dist-info/WHEEL usr/lib/python3/dist-packages/ipaddr-2.2.0.dist-info
v/lib/python3.11/site-packages/ipaddr-2.2.0.dist-info/top_level.txt usr/lib/python3/dist-packages/ipaddr-2.2.0.dist-info
v/lib/python3.11/site-packages/ipaddr.py usr/lib/python3/dist-packages